## Site settings
##############################################
title: "siimple"
version: "3.1.1"
url: "https://www.siimple.xyz"
## Theme configuration
color: "blue"
## Navbar links
links:
    - title: "Docs"
      url: "https://docs.siimple.xyz"
## Cookies settings
cookies:
    analytics: "UA-70800807-2"
    path: "/"
    domain: ".siimple.xyz"


## Build settings
##############################################
env: "production"
permalink: "none" 
theme: "siimple-theme"
exclude: ["README.md","LICENSE","app.yaml","dispatch.yaml","bower_components/","node_modules/"]
# Sass build settings
sass:
    style: "compressed"
    load_paths: ["bower_components", "_sass"]

