# Build configuration
env: "production"
exclude: ["README.md","LICENSE","app.yaml","dispatch.yaml","bower_components/"]
sass:
    load_paths:
        - _sass
        - bower_components

# Website configuration
title: "siimple"

# Navbar configuration
navbar_title: "siimple"
navbar_social: ["twitter", "github"]

# Footer configuration
footer_projects: ["siimple"]
footer_social: ["github", "twitter", "gitter"]
footer_links: ["privacy"]

# Urls
documentation_url: "https://docs.siimple.xyz"
contribute_url: "https://github.com/siimple/siimple/blob/develop/.github/CONTRIBUTING.md"


